swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
 #Ajout des endpoints         
  /accounts/{accounts_id}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Banking Module
      summary: User's accounts transaction API
      description: API for fetching a list of transaction for a specific account
      parameters:
         $ref: '#/parameters/AccountIDParam'
      produces:
        - application/json
      responses: 
        '200':
          description: Transaction retrieved successully
          schema:
            $ref: '#definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/{transaction_id}/infos:
    post:
      security:
        - Bearer: []
      tags:
        - Banking Module
      summary: Add info for a specific transaction
      description: API to add info
      parameters:
      - in: body
        name: body
        description: infos transaction Payload
        required: true
        schema:
          $ref: '#/definitions/infosValues'
      responses: 
        '200':
          description: info transaction  updated successully
          schema:
            $ref: '#/definitions/UserCategoriesResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Banking Module
      summary: update info transaction string
      description: API to update info
      parameters:
         #$ref: '#/parameters/TransactionIDParam'
        - in: body
          name: body
          description: info name payload
          required: true
          schema:
            $ref: '#definitions/infosValues'
      responses:
        '200':
          description: infos transaction  updated successully
          schema:
            $ref: '#definitions/UserCategoriesResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete: 
      security:
        - Bearer: []
      tags:
        - Banking Modules
      summary: Delate transaction infos
      description: API to delete transaction infos note and categories
      parameters: 
         $ref: '#parameters/TransactionIDParam'
      responses:
        '200':
          description: infos transaction  updated successully
          schema:
            $ref: '#definitions/UserCategoriesResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/{transaction_id}:
    get:
      security:
        - Bearer: []
      tags:
        - Banking Module
      summary: Transaction edit API
      description: API for editing notes and categories of transaction
      parameters:
        #$ref: '#/parameters/TransactionIDParam'
        - in: body
          name: body
          description: Transaction change Payload
          required: true
          schema:
            $ref: '#/definitions/TransactionDetailUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details updated successully
          schema:
            $ref: '#definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
# Fin de l'ajout
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
#Ajout des paramètres
parameters:
  AccountIDParam:
    name: accounts_id
    in: path 
    description: Unique identifier used to identify the account ressource
    required: true
    type: string
  TransactionIDParam:
    name: transaction_id
    in: path
    description: Unique identifier used to identify the transaction ressource
    required: true
    type: string 
#Fin de l'ajout
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  infosValues:
    type: object
    properties:
      name:
        type: string
      group:
        type: string
    required:
      - name
  UserCategoriesResponse:
    type: object
    properties:
      status: 
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            group:
              type: string
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
        description: Result of the request
    message:
      type: string
      description: Additional information about the result
    body:
      type: object
      properties:
        time-span:
          type: object
          properties:
            start-date:
              type: string
              format: date-time
              description: Start date of the time span
            end-date:
              type: string
              format: date-time
              description: End date of the time span
      data:
        type: object
        properties:
          transaction:
            type: array
            items:
              $ref: '#/definitions/Transaction'
    required:
      - status
      - message
      - body
  Transaction:
    type: object
    properties:
      id:
        type: integer
        description: Transaction ID
      account-id:
        type: string
        description: transaction specific account ID
      date:
        type: object
        properties:
          orderDate:
            type: string
            format: date-time
          validationDate:
            type: string
            format: date-time
            description: Transaction date and time
      description:
        type: string
        description: short transaction description or title
        amount:
          $ref: '#/definitions/TransactionAndCurrency'
      creditDebitIndicator:
        type: string
        enum:
          - Credit
          - Debit
        description:
          Indicates wheter the balance is a credit or a debit balance
      type:
        type: string
      note:
        type: string
      transactionRelatedBalance:
        type: object
        description: balance of the transaction-specific account
        properties:
          oldBalance:
            $ref: '#/definitions/Balance'
          newBalance:
            $ref: '#definitions/Balance'
  AccountId:
    description: A unique and immutable identifier used to identify the account resource
    type: string
    minLenght: 1
    maxLenght: 40
  Balance:
    type: object
    properties:
      account-id:
        $ref: '#/definitions/AccountID'
      amount:
        $ref: '#definitions/AmountAndCurrency'
      dateTime:
        description: Date and time of the balance amount record
        type: string
        format: date-time
      balanceType:
        description: 'Type of the balance'
        type: string
        enum:
          - Available Balance
          - Current Balance
  AmountAndCurrency:
    type: object
    properties:
      amount:
        $ref: '#definitions/Amount'
    required:
      - amount
      - currency
    additionalProperties: false
  Currency:
    type: string
    pattern: '^\d{A-Z}\.\d{1,5}$'
  Amount:
    type: string
    pattern: '^\d{1,13}\.\d{1,5}$'
  TransactionDetailUpdate:
    type: object
    properties:
      note:
        type: string
      category:
        type: integer

      
